### ISSUE TITLE
Erroneous "/" after file name "control.xml/"

### ISSUE THREAD

**Issue by StefanBruens** [yast/skelcd-control-openSUSE#109]
The "/" after the filename should not be there, and it was not before the last change.

https://github.com/yast/skelcd-control-openSUSE/blob/9e46374dc91745e4355c9ddbc8058c6c65380839/package/skelcd-control-openSUSE.spec#L135

**Comment by StefanBruens** [comment]
Bad commit:

https://github.com/yast/skelcd-control-openSUSE/commit/c5e2b30ae60196059134db87e0c462b67d32618f#diff-77ddf3e4d9ff2f8ba3ec203b18f96503

**Comment by StefanBruens** [comment]
Likely fixed with PR #108

**Comment by jreidinger** [comment]
yes, fixed
